name: flutter_openweatherapi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Updated to a compatible version
  weather: ^3.1.1
  cupertino_icons: ^1.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/weather.png
    - assets/images/winter.jpg
    - assets/images/sunny.jpg
    - assets/images/auntum.jpg
    - assets/images/cloudy.jpg
    - assets/images/weather_icon.png
    - assets/images/globe.png
